### PR TITLE
Added support to set output file via mocha's reporter options.

### PR DESCRIPTION
**Pull request by mbaumgartl**

### CODE REVIEW

**Comment by SimenB** [comment]
:+1:

**Comment by issacg** [comment]
Once upon a time, there was no output file and the mocha output would simply be redirected into a file which I'd suggested to be called mocha.json

I know that there's support on the parser task to specify a filename.

@m-oles, in your opinion, would it make sense to patch this side, and add glue from the task's UI to support this in Bamboo?

I sorta voulenteer (sorta meaning I'm not sure exactly *when* I'll have the few hours to hack at the Java side :))

**Comment by issacg** [comment]
I think I prefer #7 to this.  While --reporter-options fits naturally into mocha, environment variables fit easier into CI in general in my experience...

**Comment by SimenB** [comment]
Well, I could do #8 again. It tries using options, but fallbacks to the env variable (or utlimately mocha.json).

If you are the guys maintaining the plugin for Atalssian, can you tell me why you don't parse the standard JSON-output from Mocha?

To make the standard JSON output work consistently with the Bamboo-parser, I had to do something like this.

Gulp task for parsing

The try/catch isn't necessary, but the parsing of the output-data was

**Comment by issacg** [comment]
I'm not maintaining the Atlassian side.  I'm just trying to help things out, and happened to be the guy who wrote the original solution (just for mocha, not the whole Bamboo plugin) before Atlassian picked it up and started maintaining it.

I'm not really sure what you're trying to do above.

Why don't you just run the mocha runner task in each subfolder, which will accomplish what you seem to be trying to do, based on the code snippets + screenshots you've sent to date.

Then you can run each test suite separately, have each of them in it's own file (even without any patches), parse them separately and clean up the results separately.

I still think that allowing Bamboo to pass an output file to Mocha is a helpful idea, but it's not really needed in your use-case.

**Comment by SimenB** [comment]
When running from gulp, `cwd` is the directory the gulpfile is. I could of course change the `cwd` to be w/e subfolder I want, and run the tests from there. Now I output the files into a build folder with every other assets though, so the cleanup is just deleting that one folder.

I did the above before I found this plugin (the reporter used there puts the output from any other reporter in Mocha into a file, not just JSON, and not just for Bamboo's parser). It was just an example of what differs from the Mocha's JSON-output, and Bamboo's version. Doesn't have anything to do with using this plugin.

**Comment by issacg** [comment]
I understand better now, thanks for clarifying.

You can still just have gulp run mocha in the appropriate places, and it will write the mocha.json to the appropriate folder...

As to why I didn't want to parse Mocha's JSON, again I wanted output that would give me the information that Bamboo wanted in a way that would be easy for me to write the Java code.  Patches to the Java side are probably welcome if you really want :)

**Comment by SimenB** [comment]
Sure I can provide a PR.

Anyways, back to the issue at hand. Do you want me to redo #8? It allows both `reporterOptions` and an env variable, reading both at invocation, and not at `require`. I'll add some documentation as well.

**Comment by mbaumgartl** [comment]
@issacg, I don't understand your concerns against `reporterOptions`. It's just another way to set reporter's output file. One can use the environment variable if Mocha is run from command line or the `reporterOption` interface if it is run implicitly via grunt/gulp.

**Comment by mbaumgartl** [comment]
Never mind! I can solve my problem using grunt-env and the environment variable. Can you update the NPM version, please?

**Comment by issacg** [comment]
Sorry for dropping the ball on this...  (Though I'm happy you found a workaround) - without this PR (or 7), npm is up-to-date with master, isn't it?

**Comment by SimenB** [comment]
@issacg Could you reply to my question above? :smile:

**Comment by issacg** [comment]
Sure.  My understanding, looking at the PRs again, is that at the end, this PR is enough for you.  The PR looks clean, but what's going to add the option to the command-line?  AFAIK, the official Node.js Bamboo plugin won't support it, will it?

**Comment by SimenB** [comment]
> My understanding, looking at the PRs again, is that at the end, this PR is enough for you. 

This PR covers my use-case, yes.

> what's going to add the option to the command-line?

What do you mean? While this will overwrite env variable if used, unless you explicitly use `reporterOptions` it'll behave as before.

**Comment by mbaumgartl** [comment]
@issacg: Current NPM version contains MOCHA_FILE environment variable. Thanks!

**Pull request merged**
