### PR TITLE
Modify properties order on failer

### PR DESCRIPTION
**Pull request by horiuchi**
When an error occurs, it has been an error on the Bamboo v5.9.4.

### CODE REVIEW

**Comment by issacg** [comment]
I don't understand what this is supposed to solve.  Can you elaborate?

**Comment by horiuchi** [comment]
Until now the result json of including failures was occurred parse error on Bamboo's `Mocha Test Parser`.
This fix came to be correctly parsed error result json.

via: https://bitbucket.org/atlassian/bamboo-nodejs-plugin/src/fb4e73152e9b8c4ef6cf0759a50dba5c86dc5695/src/main/java/com/atlassian/bamboo/plugins/nodejs/tasks/mocha/parser/MochaSuite.java?at=master&fileviewer=file-view-default#MochaSuite.java-24

**Comment by rex** [comment]
This seems like a personal preference that belongs in a fork, not in the mainline package.

**Comment by horiuchi** [comment]
Oh, I see. Thank you!

**Pull request closed without merging**
